### ISSUE TITLE
SerialUSB fails while linking

### ISSUE THREAD

**Issue by vladkozlov69** [Wiz-IO/framework-wizio-pico#45]
Hello,

I am trying a code provided with SerialUSB.

Getting error while linking:

> .pio/build/raspberry-pi-pico/src/main.cpp.o:(.rodata._ZTV9SerialUSB[_ZTV9SerialUSB]+0x30): undefined reference to `HardwareSerial::begin(unsigned long, int, bool)'

However I got it working when changed SerialUSB parent class from HardwareSerial to Stream.

**Comment by Wiz-IO** [comment]
here was the problem: old uint8_t ... new int :)
https://github.com/Wiz-IO/framework-wizio-pico/commit/d0c42a845217d78a5f82c281ba8b1c16224d7df6#diff-d4c6a8a701a50946f1619cf37c09cf932bee992d1083e29db4d8593fed235a1a
