### ISSUE TITLE
Error installing framework wizio pico

### ISSUE THREAD

**Issue by aepub** [Wiz-IO/framework-wizio-pico#54]
"I encountered the following error while using framework wizio pico. What should I do?"? Am I the wrong person?
![11111](https://user-images.githubusercontent.com/44573941/228729195-a7bef593-04d7-47c3-8213-66e1db957500.jpg)
PIO Core Call Error: "Platform Manager:
 Installing git+https://github.com/Wiz-IO/framework-wizio-pico\r\ngit version 2.20.1.windows.1\n\n\nCloning into 
'C:\\Users\\003\\.platformio\\.cache\\tmp\\pkg-installing-vo_2n6t9'...\n
Checking out files:90% (1173/1296) \r
Checking out files:91% (1180/1296) \r
Checking out files:92% (1193/1296) \r
Checking out files:93% (1206/1296) \r
Checking out files:94% (1219/1296) \r
Checking out files: 95% (1232/1296)\r
Checking out files: 96% (1245/1296) \r
Checking out files: 97% (1258/1296) \r
Checking out files: 98% (1271/1296) \r
Checking out files: 99% (1284/1296) \r
Checking out files: 100% (1296/1296) \r
Checking out files: 100% (1296/1296), done.\n
Error: Could not find one of 'platform.json' manifest files in the package"
![22222](https://user-images.githubusercontent.com/44573941/228729250-06b5f3b2-0192-4cec-b1f5-12aa974a083b.jpg)

**Comment by DangerD1024** [comment]
same here...

**Comment by DangerD1024** [comment]
Have you solved it somehow?

**Comment by Wiz-IO** [comment]
Hi
the platform wizio-pico is closed
this git is only archive
